# Generated by Django 2.2.12 on 2020-05-15 12:33

from django.db import migrations

from students.models import Student


def forwards(apps, schema):
    for student in Student.objects.all().only('first_name', 'last_name', 'phone').iterator():
        student.first_name = student.first_name.capitalize()
        student.last_name = student.last_name.capitalize()
        student.phone = ''.join(i for i in student.phone if i.isdigit())
        student.save(update_fields=['first_name', 'last_name', 'phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_phone'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
