# Generated by Django 2.2.12 on 2020-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
