# Generated by Django 2.2.12 on 2020-05-15 12:33

from django.db import migrations

from teachers.models import Teacher


def forwards(apps, schema):
    for teacher in Teacher.objects.all().only('first_name', 'last_name').iterator():
        teacher.first_name = teacher.first_name.capitalize()
        teacher.last_name = teacher.last_name.capitalize()
        teacher.save(update_fields=['first_name', 'last_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_age'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
