# Generated by Django 2.2.12 on 2020-05-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=64)),
                ('specification', models.CharField(max_length=64)),
                ('count_of_students', models.PositiveSmallIntegerField()),
                ('length_of_course', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
