# Generated by Django 2.2.12 on 2020-05-22 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20200515_1251'),
        ('group', '0002_group_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
            preserve_default=False,
        ),
    ]
